# Generated by Django 5.0.2 on 2024-03-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_orderitem_status'),
        ('userpage', '0007_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userpage.address'),
        ),
    ]
