# Generated by Django 5.0.2 on 2024-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
